#!/usr/bin/env bash

set -e -u -x

export _EXPERIMENTAL_DAGGER_RUNNER_HOST="unix:///var/run/buildkit/buildkitd.sock"
DAGGER_CLI_COMMIT="4e9e5451565fe80778917f05ab88ba9ba32b7c91"
DAGGER_TMP_BINDIR="/tmp/dagger_${DAGGER_CLI_COMMIT}"
export _EXPERIMENTAL_DAGGER_CLI_BIN="$DAGGER_TMP_BINDIR/dagger"
if [ ! -f  "$_EXPERIMENTAL_DAGGER_CLI_BIN" ]; then
    mkdir -p "$DAGGER_TMP_BINDIR"
    curl "https://dl.dagger.io/dagger/main/${DAGGER_CLI_COMMIT}/dagger_${DAGGER_CLI_COMMIT}_$(uname -s | tr A-Z a-z)_$(uname -m | sed s/x86_64/amd64/).tar.gz" | tar xvz -C "$DAGGER_TMP_BINDIR"
fi

DAGGER_SRC_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
MAGEDIR="$DAGGER_SRC_ROOT/internal/mage"

cd "$MAGEDIR"

go run main.go -w "$DAGGER_SRC_ROOT" engine:dev

docker ps

export _EXPERIMENTAL_DAGGER_CLI_BIN=bin/dagger
export _EXPERIMENTAL_DAGGER_RUNNER_HOST="docker-container://dagger-engine.dev"
export _EXPERIMENTAL_DAGGER_CACHE_CONFIG="type=experimental_dagger_s3,mode=max,region=us-east-2,bucket=eks-buildkit-cache-test,manifests_prefix=manifests/gha-dev-$GITHUB_REF_NAME/gha-dev-$GITHUB_JOB/"

go run main.go -w "$DAGGER_SRC_ROOT" "$@"
